feat: checking compilation job step 11

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -75,10 +75,12 @@ jobs:
           for each_exec in "${execs[@]}"; do
             exec_extension="${each_exec##*.}"
             echo $each_exec
-            if [ $exec_extension == "a" ] && [ -f "$each_exec" ]; then
-              echo "::error title=Missing executable:: "$each_exec""
-              echo "MISSING_EXECUTABLES=true" >> $GITHUB_ENV
-              continue
+            if [ $exec_extension == "a" ]; then
+              if ! [ -f "$each_exec" ]; then
+                echo "::error title=Missing executable:: "$each_exec""
+                echo "MISSING_EXECUTABLES=true" >> $GITHUB_ENV
+                continue
+              fi
             fi
             if ! [[ -f "$each_exec" && -x "$each_exec" ]]; then
               echo "::error title=Missing executable:: "$each_exec""
